allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - yaml@2.8.3
  - defu@6.1.5
  - postcss@8.5.10
  - '@img/sharp-darwin-arm64@0.35.3'
  - '@img/sharp-darwin-x64@0.35.3'
  - '@img/sharp-freebsd-wasm32@0.35.3'
  - '@img/sharp-linux-arm64@0.35.3'
  - '@img/sharp-linux-arm@0.35.3'
  - '@img/sharp-linux-ppc64@0.35.3'
  - '@img/sharp-linux-riscv64@0.35.3'
  - '@img/sharp-linux-s390x@0.35.3'
  - '@img/sharp-linux-x64@0.35.3'
  - '@img/sharp-linuxmusl-arm64@0.35.3'
  - '@img/sharp-linuxmusl-x64@0.35.3'
  - '@img/sharp-webcontainers-wasm32@0.35.3'
  - '@img/sharp-win32-arm64@0.35.3'
  - '@img/sharp-win32-ia32@0.35.3'
  - '@img/sharp-win32-x64@0.35.3'
  - '@types/node@26.1.0'
  - sharp@0.35.3
  - js-yaml@4.1.2
  - '@img/sharp-wasm32@0.35.3'
